---
  - name: firewall rules (Ubuntu/Debian)
    ufw: rule=allow proto=tcp direction=in port={{ item }}
    loop: ['6443', '2379:2380', '10252']
    when: ansible_distribution == "Ubuntu" or ansible_distribution == 'Debian'
  
  - name: Firewall rules (Centos/(RHEL))
    firewalld: state=enabled port={{ item }}
    loop: ['6443/tcp', '2379:2380/tcp', '10252/tcp']
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: Check if Kubernetes has already been initialized.
    stat: path=/etc/kubernetes/admin.conf
    register: kubernetes_init_stat

  - name: Initialize Kubernetes cluster 
    command: >
      kubeadm init
      --pod-network-cidr={{ kubernetes_pod_network }}
    when: not kubernetes_init_stat.stat.exists 
    register: cluster_created

  - name: Check if kubernetes user .kube directory has already been created.
    stat: path=/home/kubernetes/.kube/config
    register: kubernetes_user_folder

  - name: Create .kube folder with config for kubernetes user.
    block:

      - name: Create .kube folder inside home.
        file: path=/home/kubernetes/.kube state=directory

      - name: Copy config file.
        copy: src=/etc/kubernetes/admin.conf dest=/home/kubernetes/.kube/config remote_src=yes

      - name: Change permissions on folder.
        file: path=/home/kubernetes/.kube/config owner=kubernetes group=kubernetes

    when: not kubernetes_user_folder.stat.exists

  - name: Deploy flannel networking
    command: >
      kubectl apply -f
      https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    become_user: kubernetes
    when: cluster_created.changed
  
  # - include_tasks: kubernetes-addons.yml